### ISSUE TITLE
Meeting times

### ISSUE THREAD

**Issue by ozzieba** [blanksblanks/project-cookie#1]
I believe we're supposed to officially confirm 3 meeting times over the next week, and submit them by midnight tonight.

The Wiki lists 3 meeting times:
Wed 3/18 before 2:00pm
Thu 3/19 before 2:40pm
Fri 3/20 before 4:00pm

Given that these are supposed to be over the next week, I assume the intention was 2/18, 2/19, and 2/20, rather than March. Please correct me if I'm wrong.

Personally I can do any of those times, except on Friday I need to leave the city no later than 3:30 or so. Ideally I'd want to meet before noon, though I could theoretically make it as late as 2:45-3pm.
Can we confirm that everyone is comfortable with those dates/times?

**Comment by ch2994** [comment]
I can meet any time of the week before 12:00pm.

**Comment by jzf2101** [comment]
See #3  for meeting on 2/18
