### ISSUE TITLE
Document App Setup and Github Get Request Code

### ISSUE THREAD

**Issue by jzf2101** [blanksblanks/project-cookie#12]
@ozzieba we need your code doucmented for the hackday on Saturday.  Thanks!

**Comment by ozzieba** [comment]
Update: just realized I can set 'localhost:3000' as the Github key redirect URL. So now if you just access the site using localhost:3000 you should be able to use GitHub (and Google) API requests

**Comment by jzf2101** [comment]
@ozzieba Can you close this if your commenting is done?
