### ISSUE TITLE
Project outline

### ISSUE THREAD

**Issue by ozzieba** [blanksblanks/project-cookie#2]
I believe we need to submit a project outline tonight, including a 1-paragraph description and 3 milestones.

Since I do not know of any concrete plans for the project, I offer my half-baked ideas to start the discussion. Please let me know if you've already discussed any/all of these issues and come to any conclusions, so I know where we are.

I gather that we've pretty much settled on the GitHub visualization idea. I'd like to get a better idea of the types of visualizations we want. 
If we focus on individual users trying to understand their overall contribution patterns, we could:
-- Track overall number of commits over time, by project, by language, etc
-- Track Source Lines of Code or other simple (and dubious?) measures of overall productivity, or perhaps something more sophisticated
--Replicate GitHub's built-in graphs, on a per-user basis rather than per-repository
--Track commits which are subsequently un-done by other peoples' revisions, vs those that stay for a while
--Other?

Off the top of my head, we could break the project up as follows:
--Set up a working Node server. We could use a cloud service, or perhaps a physical machine. I have a few Linux servers that could run the stack natively or under a VM.
--Get the data: define precisely what data we need, and get it. This would probably involve creating functions that get a user's commit data from a local git repo or GitHub, and storing it in Mongo. We could also get other data, eg entire repos that the user has contributed to, or repos that are forks/parents of those projects.
--Set up Express to field requests for data by interfacing with Mongo and git, figure out what to store, when to update stale data, etc.
--I know essentially nothing about D3, except the description on its homepage. We want to figure out whether we want to run all/most of the transformations on the client side, and simply serve D3.js as a file with the raw data, or do some or all of the data manipulation on the server side with Express/Node. Thoughts welcome.
--We need to build a reasonable interface using Angular and the visualizations themselves using D3

Not sure exactly where we'd put milestones, let me know what you guys think, and/or if I'm completely missing the point in some way. I have no MEAN/JS experience outside this course, so I may very well be completely confused about the architecture/workflow. If so, please suggest improvements/complete rehauls for these ideas, but be nice ;). 

Also, I have seen no Facebook activity since the initial "Hello hello team" from Nina on Wednesday. Is there another group chat going on?

Finally, let me know if anyone/everyone wants to meet today to work on this. I'm currently at home, but could get to campus pretty quickly (I live on 109th St). Otherwise, doing this all online is fine with me.

**Comment by ch2994** [comment]
Nice work Oz!! Are you free at 7pm tonight? We can meet at the library to wrap things up.

**Comment by jzf2101** [comment]
See [Wiki](https://github.com/blanksblanks/project-cookie/wiki) for updated project outline and milestones
