### ISSUE TITLE
Group Meeting 1 (2-15-2015)

### ISSUE THREAD

**Issue by ch2994** [blanksblanks/project-cookie#3]
```
 The following is the minutes from today's group meeting. If there is anything you want to add, please feel free to make the change.
```

Milestones:
[Week1] Understand d3 and Github API and create a WIKI page for the Github API. 
[Week2] Make the static mockups for the visualization graphs.
[Week3] Set up the mechanism to request data and information from Github.
[Week4] Make the visualization live.

```
 Also, the three tentative meeting time slots are all on Wednesday, February 18th,  between 10pm to 1pm .
```

**Comment by jzf2101** [comment]
Thanks for updating this I'm archiving for reference
