### ISSUE TITLE
Group Meeting 2-25-2015 10:00 AM

### ISSUE THREAD

**Issue by ozzieba** [blanksblanks/project-cookie#4]
1. Thanks to everyone who updated the Wiki
2. I added a build of Lev's Columbia Angular Generator to our repo app as a template
3. I have a server working at http://cpe-74-66-80-66.nyc.res.rr.com:3000/ if you want to try it out
4. At the moment I've gotten Google and GitHub sign-ins to work, and basic requests from the GitHub API.
5. Next up: we need concrete plans for the specific visualizations we want, and plans to make that happen. I will also clean up the skeleton code and add specific TODO templates with specific tasks for each of us to work on, was going to do that last week but didn't get to it

**Comment by blanksblanks** [comment]
done
